#!/bin/bash
#
# Script to downgrade iPhone 4 GSM (iPhone3,1) to 4.3.5
#

echo -e "Please drag-n-drop your iOS 7.1.2 IPSW: "
read IPSWBase

echo -e "Please drag-n-drop your iOS 4.3.5 IPSW: "
read IPSWLow
echo "Now the magic begins..."

./ipwndfu/ipwndfu -p
./cherryflower/idevicerestore -t $IPSWBase

echo -e "\n\n Please enter your device ECID (The numerical part of the string above that says \"SHSH saved to 'shsh/[YOUR IPHONE'S ECID HERE]-iPhone3,1-7.1.2.shsh'\") : "
read DEVECID

zcat < ./cherryflower/shsh/$DEVECID-iPhone3,1-7.1.2.shsh > ./cherryflower/shsh/$DEVECID-iPhone3,1-7.1.2.plist
plutil -convert xml1 ./cherryflower/shsh/$DEVECID-iPhone3,1-7.1.2.plist

./cherryflower/cherryJB $IPSWLow $DEVECID\_iPhone3,1_4.3.5_8J2_Custom.ipsw -memory -derebusantiquis $IPSWBase -a ./cherryflower/shsh/$DEVECID-iPhone3,1-7.1.2.plist

./cherryflower/idevicerestore -e -w $DEVECID\_iPhone3,1_4.3.5_8J2_Custom.ipsw
